melusine/utils/multiprocessing.py, melusine/utils/transformer_scheduler.py
This PR tries to fix [this issue](https://github.com/MAIF/melusine/issues/1)
A [joblib.Parallel](https://joblib.readthedocs.io/en/latest/generated/joblib.Parallel.html#joblib.Parallel) instance is used to launch parallelisation, with a `prefer=process` keyword set
The notebooks in `tutorial/` all seem to be working 
By using joblib there is no `progress bar` anymore. I could not find a clean way to use `tqdm` with it
=> joblib as backend to apply_by_multiprocessing

melusine/nlp_tools/embedding.py, melusine/nlp_tools/phraser.py, melusine/utils/multiprocessing.py, melusine/utils/streamer.py, melusine/utils/transformer_scheduler.py, setup.py
This pull request enables the progress_bar (tqdm) with joblib (multiprocessing.py)
It fixes an issue about the transformer_scheduler. 
Indeed there were a problem when I executed the tutorial02 and every tutorial that use the transorformer_scheduler. The modifications implemented in this branch fixed this issue.
Finally it adds a precision in the requirements 'tensorflow>=1.10.0,<=1.13.1'
Indeed if the setup.py installs tensorflow 2.0 then an issue occurs
=> Transformer

README.md
=> Fix double colon :)

melusine/models/train.py, melusine/nlp_tools/embedding.py, melusine/nlp_tools/phraser.py, melusine/nlp_tools/tokenizer.py, melusine/prepare_email/cleaning.py
Optimizing NeuralModel class, updating logger file and deleting "remove apostrophe" in the clean text function
=> optimize NeuralModel class

melusine/models/modeler_semantic.py, melusine/models/train.py, melusine/nlp_tools/tokenizer.py, melusine/prepare_email/metadata_engineering.py, melusine/summarizer/keywords_generator.py, melusine/utils/transformer_scheduler.py, tests/integration_test/test_classification.py, tutorial/tutorial08_full_pipeline_detailed.ipynb, tutorial/tutorial12_semantic_analysis.ipynb
SemanticDetector : Anti seed words can be specified (prevent undesired theme detection)
SemanticDetector: Updated tutorial 12
Dict Compatibility: dict object can be fed to most Melusine objects (Transformer Scheduler, NeuralModel, Keywords generator) => Performance gain when input data are fed to the model one at a time
Dict Compatibility: Updated tutorial 08 (full pipeline detailed)
=> Improve SemanticDetector and Added dict input compatibility

melusine/nlp_tools/embedding.py
Moved parameters init from train to init function. To allow user to modify parameters
=> Edit on embedding class

melusine/config/conf.json
Minor fix : Typo in extract_from regex
=> Minor fix regex

melusine/config/conf.json, melusine/prepare_email/mail_segmenting.py
Add Order when segmenting into "Hello","Greetings", etc. to give priority to some Tag thanks to segmenting_order config list
=> Add Order when segmenting emails

melusine/prepare_email/mail_segmenting.py
Check for flag words like date or time before tag a sentence to Hello, Greetings or Thanks
=> Tag flagged sentence to body 

setup.py
Adding the file names.csv to setup.py so it will be downloaded also through pip install melusine.
=> Add names.csv file to setup.py

melusine/config/config.py, melusine/data/dashboard_app.py, melusine/models/attention_model.py, melusine/models/modeler_semantic.py, melusine/models/train.py, melusine/nlp_tools/embedding.py, melusine/nlp_tools/phraser.py, melusine/nlp_tools/tokenizer.py, melusine/prepare_email/mail_segmenting.py, melusine/prepare_email/metadata_engineering.py, melusine/summarizer/keywords_generator.py, melusine/utils/printer.py, melusine/utils/transformer_scheduler.py, setup.py, tests/integration_test/test_classification.py, tests/unit_tests/nlp_tools/test_tokenizer.py
I propose this work around to save bert model in tensorflow and also fixing loading of classic models
=> Fixing save and load model

requirements_dev.txt
still trying to fix incompatibility for travis build
=> fixing version conflict travis

setup.py
Add connector path to setup.py to enable its import
Fixes # (issue)
Please delete options that are not relevant.
=> Closes #85 hotfix to enable import of connectors

.github/workflows/main.yml, melusine/data/dashboard_app.py, melusine/models/neural_architectures.py, melusine/models/train.py, setup.py
Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.
Please provide enough information so that others can review your pull request:
Explain the details for making this change. What existing problem does the pull request solve ?
Test plan (required)
Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please …
=> Cleanup dependencies

setup.py
=> :fix: recursive glob

melusine/prepare_email/metadata_engineering.py
PR to correct the error explained in #134.
=> [#134] Add "other" value to the training of label encoder 

melusine/summarizer/keywords_generator.py, setup.py
Update scikit-learn and fix API breaking change (TfIdfVectorizer.get_feature_names_out)
=> Update scikit learn version

docs/tutorials/00_GettingStarted.md, docs/tutorials/05a_MelusineDetectors.md, docs/tutorials/05b_MelusineDetectorsAdvanced.md, docs/tutorials/06_Configurations.md, docs/tutorials/07_BasicClassification.md
Fix project root to display code blocks in tutorials
=> :memo: Display code blocks in tutorials

docs/tutorials/08_MelusineRegex.md, mkdocs.yml
Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.
Please provide enough information so that others can review your pull request:
Explain the details for making this change. What existing problem does the pull request solve ?
Adds docs and example for MelusineRegex
Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.
Please delete options that are not relevant.
=> Addition of the MelusineRegex documentation

docs/tutorials/08_MelusineRegex.md, melusine/base.py, tests/regex/test_builtin_regex.py
Update the MelusineRegex tutorial.
Run the MelusineRegex `test` method within the __init__.
=> Update MelusineRegex class and tutorial
